# Generated by Django 4.2.7 on 2025-12-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='seen_by_a',
            field=models.BooleanField(default=False, help_text='User A has seen the match reveal'),
        ),
        migrations.AddField(
            model_name='match',
            name='seen_by_b',
            field=models.BooleanField(default=False, help_text='User B has seen the match reveal'),
        ),
    ]
