# Generated by Django 4.2.7 on 2025-11-27 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interest_tags',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('PHYS', 'Physics'), ('MATH', 'Mathematics'), ('ECON', 'Economics'), ('PSYC', 'Psychology'), ('LAW', 'Law'), ('MUSIC', 'Music'), ('ART', 'Art, Design and Architecture'), ('MAN', 'Management'), ('POL', 'Political Science'), ('LIT', 'Literature'), ('OTHER', 'Other')], max_length=10)),
                ('study_level', models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PHD', 'PhD')], max_length=5)),
                ('about_text', models.TextField(blank=True, max_length=500)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.interesttag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
