# Generated by Django 4.2.7 on 2025-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('EDU_PRIMARY', 'Primary Education (Classroom Teaching)'), ('EDU_SCIENCES', 'Educational Sciences'), ('EDU_TEFL', 'Teaching English as a Foreign Language'), ('PHYS', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('MBG', 'Molecular Biology and Genetics'), ('GD', 'Graphic Design'), ('FA', 'Fine Arts'), ('IAED', 'Interior Architecture and Environmental Design'), ('CD', 'Communication and Design'), ('UDLA', 'Urban Design and Landscape Architecture'), ('ARCH', 'Architecture'), ('ECON', 'Economics'), ('PSYC', 'Psychology'), ('POL', 'Political Science and Public Administration'), ('HIST', 'History'), ('IR', 'International Relations'), ('ACL', 'American Culture and Literature'), ('ARCHAE', 'Archaeology'), ('PHIL', 'Philosophy'), ('ELIT', 'English Language and Literature'), ('TRANS', 'English, French Translation and Interpretation'), ('TLIT', 'Turkish Literature'), ('BUS', 'Business Administration'), ('LAW', 'Law'), ('CS', 'Computer Engineering'), ('EE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering'), ('MUSIC', 'Music'), ('THEATRE', 'Theatre'), ('IST', 'Information Systems and Technologies'), ('TOH', 'Tourism and Hotel Management')], max_length=20),
        ),
    ]
