# Generated by Django 4.2.7 on 2025-12-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('EDU_PRIMARY', 'Temel Eğitim (Sınıf Öğretmenliği)'), ('EDU_SCIENCES', 'Eğitim Bilimleri'), ('EDU_TEFL', 'Yabancı Dil Olarak İngilizce Öğretimi'), ('PHYS', 'Fizik'), ('CHEM', 'Kimya'), ('MATH', 'Matematik'), ('MBG', 'Moleküler Biyoloji ve Genetik'), ('GD', 'Grafik Tasarımı'), ('FA', 'Güzel Sanatlar'), ('IAED', 'İç Mimarlık ve Çevre Tasarımı'), ('CD', 'İletişim ve Tasarımı'), ('UDLA', 'Kentsel Tasarım ve Peyzaj Mimarlığı'), ('ARCH', 'Mimarlık'), ('ECON', 'İktisat'), ('PSYC', 'Psikoloji'), ('POL', 'Siyaset Bilimi ve Kamu Yönetimi'), ('HIST', 'Tarih'), ('IR', 'Uluslararası İlişkiler'), ('ACL', 'Amerikan Kültürü ve Edebiyatı'), ('ARCHAE', 'Arkeoloji'), ('PHIL', 'Felsefe'), ('ELIT', 'İngiliz Dili ve Edebiyatı'), ('TRANS', 'İngilizce, Fransızca Mütercim ve Tercümanlık'), ('TLIT', 'Türk Edebiyatı'), ('BUS', 'İşletme'), ('LAW', 'Hukuk Fakültesi'), ('CS', 'Bilgisayar Mühendisliği'), ('EE', 'Elektrik – Elektronik Mühendisliği'), ('IE', 'Endüstri Mühendisliği'), ('ME', 'Makine Mühendisliği'), ('MUSIC', 'Müzik'), ('THEATRE', 'Tiyatro'), ('IST', 'Bilişim Sistemleri ve Teknolojileri'), ('TOH', 'Turizm ve Otel İşletmeciliği')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_level',
            field=models.CharField(choices=[('PREP', 'Hazırlık'), ('UG', 'Lisans'), ('GR', 'Yüksek Lisans'), ('PHD', 'Doktora')], max_length=5),
        ),
    ]
